<?php


namespace Seatplus\Web\Tests\Integration;


use Seatplus\Auth\Models\Permissions\Permission;
use Seatplus\Web\Services\Sidebar\SidebarEntries;
use Seatplus\Web\Tests\TestCase;

class SidebarTest extends TestCase
{
    public function setUp(): void
    {

        parent::setUp(); // TODO: Change the autogenerated stub

        //Permission::findOrCreate('superuser');
        $this->app->make(\Spatie\Permission\PermissionRegistrar::class)->registerPermissions();
    }

    /** @test */
    public function user_without_superuser_does_not_see_access_control()
    {

        $this->actingAs($this->test_user);

        $sidebar = (new SidebarEntries)->filter();

        $this->assertFalse(array_key_exists('Access Control', $sidebar));
    }

    /** @test */
    public function user_with_superuser_does_see_access_control()
    {

        $this->actingAs($this->test_user);

        $this->test_user->givePermissionTo('superuser');

        $sidebar = (new SidebarEntries)->filter();

        $this->assertTrue(array_key_exists('Access Control', $sidebar));
    }

    /** @test */
    public function user_with_view_access_control_does_see_access_control()
    {

        $this->actingAs($this->test_user);

        Permission::create(['name' => 'view access control']);

        $this->test_user->givePermissionTo('superuser');

        $sidebar = (new SidebarEntries)->filter();

        $this->assertTrue(array_key_exists('Access Control', $sidebar));
    }

}
