name: Laravel

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  laravel:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Setup PHP, with composer and extensions
      uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
      with:
        php-version: '7.4'
        extensions: mbstring, dom, fileinfo
        coverage: xdebug #optional
    - name: Redis Server in GitHub Actions
      uses: supercharge/redis-github-action@1.1.0
      with:
        # Redis version to use
        redis-version: 5 # optional, default is latest
    - name: Test & publish code coverage
      uses: paambaati/codeclimate-action@v2.6.0
      env:
        CC_TEST_REPORTER_ID: 1ba66b56bc5a04c17474d52e94124cb04d4a520c7c46a01ace9ce25e7b58b85d
      with:
        coverageCommand: vendor/bin/phpunit --coverage-clover build/logs/clover.xml
        debug: false

  front-end-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: install npm packages
        run: npm install
      - name: run npm tests
        run: npm test
